// Code generated by Icestudio 0.3.0-rc-dev
// Wed, 08 Mar 2017 23:51:23 GMT

// Testbench template

`default_nettype none
`define DUMPSTR(x) `"x.vcd`"
`timescale 10 ns / 1 ns


module main_tb;
 
 // Simulation time: 100ns (10 * 10ns)
 parameter DURATION = 10;
 
 // Input/Output
 wire [3:0] out;
 
 // Module instance
 main MAIN (
  .vba3212(out)
 );
 
 initial begin
  // File were to store the simulation results
  $dumpfile(`DUMPSTR(`VCD_OUTPUT));
  $dumpvars(0, main_tb);
 
  // TODO: initialize the registers here
  // e.g. value = 1;
  // e.g. #2 value = 0;
 
  #(DURATION) $display("End of simulation");
  $finish;
 end
 
endmodule
